const foods = [
       "Moong Dal (Yellow)",
       "Massor Dal",
       "Palak Panner",
       "Chawli Ki Sabji",
       "Allo Ki Sabji",
       "Bangan",
       "French Beans",
       "Orange Dal (High Protein)",
       "Moong Chawal",
       "Kadhi Chawal",
       "Simla Mirchi Besan",
       "Poha",
       "Rawa",
       "Besan Chilla",
       "Rawa Chilla",
       "Maggie",
       "Bhel",
       "Toast Sandwich",
       "Vegetable Sandwich",
       "Channa Dal",
       "Cabbbage Ki Sabji",
       "Roti",
       "Chole",
       "Rajma",
       "Only Onion Ki Sabji",
       "Pasta",
       "Matar Panner",
       "Mix Veg With Panner"
    ]